apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
spec:
  selector:
    matchLabels:
      app: nginx
  replicas: 1
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: nginx:1.21.1
        ports:
        - containerPort: 80
        volumeMounts:
        - name: docker
          mountPath: /run/containerd/containerd.sock
      volumes:
      - name: docker
        hostPath:
          path: /run/containerd/containerd.sock

